### ISSUE TITLE
Links to Julia documentation broken

### ISSUE THREAD

**Issue by jonas-schulze** [JuliaComputing/JuliaHub-Feedback#112]
Searching the documentation gives results for the language itself (which is awesome 🚀). However, the URL to the Julia docs are different from the ones to some packages, which JuliaHub doesn't distinguish:

* https://juliahub.com/ui/Documentation?q=relative%20error offers
* https://juliahub.com/docs/julia/THl1k/1.5.3/base/base/#Errors instead of
* https://docs.julialang.org/en/v1/base/base/#Errors

On top of that, `1.5.3` is not the most recent version of Julia, in case that's a hint of some other issue.

**Comment by pfitzseb** [comment]
Fixed now.
