### ISSUE TITLE
Front page of Packages search shows Julia as v1.6.1 instead of 1.6.3

### ISSUE THREAD

**Issue by dalejordan** [JuliaComputing/JuliaHub-Feedback#132]

**Comment by fonsp** [comment]
https://juliahub.com/ui/Packages

<img width="1063" alt="Schermafbeelding 2021-12-11 om 18 10 33" src="https://user-images.githubusercontent.com/6933510/145685397-e530ac1a-3607-4042-bd21-270915ff8c73.png">

**Comment by LilithHafner** [comment]
Related, links to julia source code in search results link to 1.6.1
<img width="1440" alt="Screen Shot 2022-11-20 at 5 30 08 PM" src="https://user-images.githubusercontent.com/60898866/202899637-a685cfce-5cb1-4150-ace2-64c199aa63cb.png">

**Comment by vdayanand** [comment]
Thanks for reporting.  This is fixed now
