### ISSUE TITLE
MIT license is UNKNOWN

### ISSUE THREAD

**Issue by cjdoris** [JuliaComputing/JuliaHub-Feedback#147]
On the page for PythonCall (https://juliahub.com/ui/Packages/PythonCall/WdXsa/0.9.5) the license is marked as UNKNOWN, even though it is MIT licensed (https://github.com/cjdoris/PythonCall.jl/blob/main/LICENSE).

If you search for "PythonCall" however, it correctly shows the license as MIT in the search results.

**Comment by vdayanand** [comment]
Thanks for reporting, this is fixed now.

**Comment by pfitzseb** [comment]
Seems to be fixed now:
![image](https://user-images.githubusercontent.com/6735977/185865262-4f4fc070-1c69-4c38-8a50-dae0d7c540cc.png)

It's possible that license detection sometimes lags behind; we'll look into why that happens.
