### ISSUE TITLE
keyboard shortcut for search

### ISSUE THREAD

**Issue by Roger-luo** [JuliaComputing/JuliaHub-Feedback#152]
It's quite common for websites supporting some basic keyboard shortcut, e.g https://docusaurus.io/

<img width="460" alt="image" src="https://user-images.githubusercontent.com/8445510/221913131-f62afd2b-c838-41ca-8d04-9f1c19c17e92.png">

It'd be nice if JuliaHub has this too

**Comment by pfitzseb** [comment]
`s` and `/` no focus the global search bar.
