### ISSUE TITLE
HTTP not listed as dependent of LoggingExtras

### ISSUE THREAD

**Issue by fonsp** [JuliaComputing/JuliaHub-Feedback#154]
HTTP depends on LoggingExtras: https://juliahub.com/ui/Packages/HTTP/zXWya/1.7.4?page=1

But HTTP is not listed as (indirect) dependent of LoggingExtras: https://juliahub.com/ui/Packages/LoggingExtras/9fRHf/0.4.0?page=2

**Comment by pfitzseb** [comment]
That's correct, but you're looking at LoggingExtras@0.4.0 specifically. 

HTTP depends on LoggingExtras versions newer than 0.4.9:
![image](https://user-images.githubusercontent.com/6735977/225013539-c944327e-a394-461a-9e95-19804c0d151c.png)

And indeed, LoggingExtras@1.0.0 lists HTTP as a direct dependent:
![image](https://user-images.githubusercontent.com/6735977/225013742-c10a4b24-0646-4c7f-92e0-b199165d46a8.png)

**Comment by fonsp** [comment]
Ahhh right, I just found this page with google and didn't check the version.

**Comment by pfitzseb** [comment]
Yeah, that's a SEO issue which we'll hopefully get to sooner rather than later...
