### ISSUE TITLE
Query.jl package is not linked, but exists.

### ISSUE THREAD

**Issue by mfiano** [JuliaComputing/JuliaHub-Feedback#155]
When [searching for `query.jl`](https://juliahub.com/ui/Search?page=1&q=query.jl&type=packages) the package in question is at the top, but it's name is not clickable/linked. However, the package has not been updated in a long time, and it does have a page for the latest package here: https://juliahub.com/ui/Packages/Query/wGX7b/1.0.0

**Comment by pfitzseb** [comment]
Thanks for the report! Looks like this will be fixed in the next version, which should be out soon™

**Comment by pfitzseb** [comment]
https://juliahub.com/ui/Packages/General/Query now exists.

**Comment by nsajko** [comment]
Not fixed. OP says:

> When [searching for query.jl](https://juliahub.com/ui/Search?page=1&q=query.jl&type=packages) the package in question is at the top, but it's name is not clickable/linked.

This still holds, the package search result for Query.jl isn't clickable: https://juliahub.com/ui/Search?q=query&type=packages

Moreover, it seems that all newly registered packages may be affected by the same, or similar, issue. For example, the package ConsensusBasedXPlots.jl was registered last week: https://github.com/JuliaRegistries/General/pull/102578

It does have a package page on JuliaHub: https://juliahub.com/ui/Packages/General/ConsensusBasedXPlots

But its search result in package search is greyed-out and isn't clickable: https://juliahub.com/ui/Search?q=ConsensusBasedXPlots&type=packages

![search](https://github.com/JuliaComputing/JuliaHub-Feedback/assets/4944410/5493b942-fef0-4b65-b35a-654ac248e51b)
