### ISSUE TITLE
Documentation search shows broken URLs

### ISSUE THREAD

**Issue by jonas-schulze** [JuliaComputing/JuliaHub-Feedback#156]
When searching for e.g. "SuiteSparse" within package documentations, the links pointing to SuiteSparseMatrixCollection's package or documentation page are broken.

* Search:
  https://juliahub.com/ui/Search?q=suitesparse&type=docs
* Broken:
  https://juliahub.com/ui/docs/SuiteSparseMatrixCollection/Nq3aJ/0.5.3/
* Expected:
  https://juliahub.com/ui/Packages/SuiteSparseMatrixCollection/Nq3aJ/0.5.5 or
  https://docs.juliahub.com/SuiteSparseMatrixCollection/Nq3aJ/0.5.5/

**Comment by pfitzseb** [comment]
Seems to work fine now.
